// lib/models/cities.dart
// Single source of truth for Indian city list.
// Used in: doctor registration, patient registration, home screen filter.
// To add a city: just add it to kIndianCities — appears everywhere automatically.

const List<String> kIndianCities = [
  // ── Metro ──
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Pune',
  'Ahmedabad',
  // ── Tier 2 ──
  'Jaipur',
  'Lucknow',
  'Surat',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Bhopal',
  'Patna',
  'Vadodara',
  'Ludhiana',
  'Agra',
  'Nashik',
  'Faridabad',
  'Meerut',
  'Rajkot',
  'Varanasi',
  'Srinagar',
  'Aurangabad',
  'Dhanbad',
  'Amritsar',
  'Allahabad',
  'Ranchi',
  'Guwahati',
  'Coimbatore',
  'Vijayawada',
  'Jodhpur',
  'Madurai',
  'Raipur',
  'Kochi',
  'Chandigarh',
  'Gurgaon',
  'Noida',
  'Thiruvananthapuram',
  'Bhubaneswar',
  'Dehradun',
  'Mysuru',
  'Mangaluru',
  'Siliguri',
  'Jalandhar',
  'Tiruchirappalli',
  'Bareilly',
  'Aligarh',
  'Moradabad',
  'Gwalior',
  'Jabalpur',
  'Warangal',
  'Hubli',
  'Cuttack',
  'Bikaner',
  'Kota',
  'Kolhapur',
  'Udaipur',
  'Solapur',
  'Ajmer',
  'Vizag (Visakhapatnam)',
  'Tirupati',
  'Nellore',
  'Guntur',
  'Puducherry',
];